server:
  port: 8082

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirect-uri: http://localhost:8082/login/oauth2/code/google
  data:
    mongodb:
      uri:
      repositories:
        type: imperative