server:
  port: 8082

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${client-id}
            client-secret: ${client-secret}
            redirect-uri: http://localhost:8082/login/oauth2/code/google
  data:
    mongodb:
      uri: ${mongodb-uri}
      repositories:
        type: imperative


  kafka:
    bootstrap-servers: ${bootstrap-server}
    template:
      default-topic: ${topic-name}