server:
  port: 8082

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 193770460733-pcmch82gqhc2l5ptbc6o8mftqmhe9m8o.apps.googleusercontent.com
            client-secret: GmhPAZ5exC3WCNAYVNLLZqh4
            redirect-uri: http://localhost:8082/login/oauth2/code/google
cloud:
  aws:
    credentials:
      access-key: YBCwZ4Raop+rB0USCJX6m1/0YPfZig1q9rgG4GWT
      secret-key: AKIAVWGPYG6YFXBBPHV4
    region:
      auto: false
      static: us-west-2


aws:
  messaging_channel: https://sqs.us-west-2.amazonaws.com/391277721520/auth-notification-queue
  access_key: AKIAVWGPYG6YFXBBPHV4
  secret_key: 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
  region: us-west-2